spring.application.name=room

spring.config.import=optional:file:${user.dir}/.env[.properties],optional:file:${user.dir}/paper-microservice-project-backend/.env[.properties]

spring.datasource.url=${ROOM_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${ROOM_SERVICE_PORT}

clients.conference.base-url=${CONFERENCE_SERVICE_URL:http://localhost:8082}
